import { mount, VueWrapper } from '@vue/test-utils'
import { Component } from 'vue'

/**
 * Mount a component with Element Plus stubs pre-configured.
 */
export function mountWithStubs(component: Component, options: Record<string, any> = {}): VueWrapper<any> {
  const defaultStubs = {
    'el-button': { template: '<button><slot /></button>' },
    'el-input': true,
    'el-tag': { template: '<span><slot /></span>' },
    'el-card': { template: '<div><slot /></div>' },
    'el-dialog': { template: '<div><slot /><slot name="footer" /></div>' },
    'el-form': { template: '<form><slot /></form>' },
    'el-form-item': { template: '<div><slot /></div>', props: ['label'] },
    'el-tabs': { template: '<div><slot /></div>' },
    'el-tab-pane': { template: '<div><slot /></div>' },
    'el-empty': { template: '<div><slot /></div>' },
    'el-skeleton': { template: '<div><slot /></div>' },
    'el-menu': { template: '<nav><slot /></nav>' },
    'el-menu-item': { template: '<div><slot /></div>' },
    'el-breadcrumb': { template: '<div><slot /></div>' },
    'el-breadcrumb-item': { template: '<span><slot /></span>' },
    'el-avatar': { template: '<div><slot /></div>' },
    'el-badge': { template: '<div><slot /></div>' },
    'el-popover': { template: '<div><slot /></div>' },
    'el-backtop': { template: '<div />' },
    'el-upload': { template: '<div><slot /></div>' },
    'el-drawer': { template: '<div><slot /></div>' },
    'el-timeline': { template: '<div><slot /></div>' },
    'el-timeline-item': { template: '<div><slot /></div>' },
    'el-select': { template: '<select><slot /></select>' },
    'el-option': { template: '<option><slot /></option>' },
    'el-table': { template: '<table><slot /></table>' },
    'el-table-column': { template: '<td><slot /></td>' },
    'el-link': { template: '<a><slot /></a>' },
    'el-row': { template: '<div><slot /></div>' },
    'el-col': { template: '<div><slot /></div>' },
    'el-icon': { template: '<i />' },
    'el-dropdown': { template: '<div><slot /></div>' },
    'el-dropdown-menu': { template: '<div><slot /></div>' },
    'el-dropdown-item': { template: '<div><slot /></div>' },
    'el-switch': true,
    'el-checkbox': true,
    'el-radio': true,
    'el-radio-group': { template: '<div><slot /></div>' },
    'el-tooltip': { template: '<div><slot /></div>' },
    'el-divider': true,
    'el-alert': { template: '<div><slot /></div>' },
    'el-result': { template: '<div><slot /></div>' },
    'el-image': true,
    'el-descriptions': { template: '<div><slot /></div>' },
    'el-descriptions-item': { template: '<div><slot /></div>' },
    'el-pagination': true,
    'el-date-picker': true,
    'el-time-picker': true,
    'el-color-picker': true,
    'el-transfer': true,
    'el-cascader': true,
    'el-tree': { template: '<div><slot /></div>' },
    'el-steps': { template: '<div><slot /></div>' },
    'el-step': { template: '<div><slot /></div>' },
    'el-collapse': { template: '<div><slot /></div>' },
    'el-collapse-item': { template: '<div><slot /></div>' },
    'el-carousel': { template: '<div><slot /></div>' },
    'el-carousel-item': { template: '<div><slot /></div>' },
    'el-affix': { template: '<div><slot /></div>' },
    'el-anchor': { template: '<div><slot /></div>' },
    'el-anchor-link': { template: '<div><slot /></div>' },
    'el-scrollbar': { template: '<div><slot /></div>' },
    'el-autocomplete': { template: '<div><slot /></div>' },
    'el-rate': true,
    'el-slider': true,
    'el-input-number': true,
    'el-select-v2': true,
    'el-skeleton-item': true,
    'el-space': { template: '<div><slot /></div>' },
    'el-statistic': { template: '<div><slot /></div>' },
    'el-page-header': { template: '<div><slot /></div>' },
    'el-virtual-list': { template: '<div><slot /></div>' },
    'el-watermark': true,
    'el-text': { template: '<span><slot /></span>' },
    'el-calendar': true,
    'el-config-provider': { template: '<div><slot /></div>' },
    'el-only-child': { template: '<div><slot /></div>' },
    'el-focus-trap': { template: '<div><slot /></div>' },
    'el-progress': true,
    'router-link': { template: '<a><slot /></a>' },
    'router-view': true,
  }

  return mount(component, {
    global: {
      stubs: { ...defaultStubs, ...(options.global?.stubs || {}) },
      ...options.global,
    },
    ...options,
  })
}